## Read more about GitHub actions the features of this GitHub Actions workflow
## at https://lcolladotor.github.io/biocthis/articles/biocthis.html#use_bioc_github_action
##
## For more details, check the biocthis developer notes vignette at
## https://lcolladotor.github.io/biocthis/articles/biocthis_dev_notes.html
##
## You can add this workflow to other packages using:
## > biocthis::use_bioc_github_action()
##
## Using GitHub Actions exposes you to many details about how R packages are
## compiled and installed in several operating system.s
### If you need help, please follow the steps listed at
## https://github.com/r-lib/actions#where-to-find-help
##
## If you found an issue specific to biocthis's GHA workflow, please report it
## with the information that will make it easier for others to help you.
## Thank you!

## Acronyms:
## * GHA: GitHub Action
## * OS: operating system

on:
  push:
  pull_request:

name: create-test-upload

## These environment variables control whether to run GHA code later on that is
## specific to testthat, covr, and pkgdown.
##
## If you need to clear the cache of packages, update the number inside
## cache-version as discussed at https://github.com/r-lib/actions/issues/86.
## Note that you can always run a GHA test without the cache by using the word
## "/nocache" in the commit message.
env:
  has_testthat: 'true'
  run_covr: 'true'
  run_pkgdown: 'true'
  has_RUnit: 'false'
  cache-version: 'cache-v1'
  run_docker: 'true'

jobs:
  build-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }}
    container: ${{ matrix.config.cont }}
    ## Environment variables unique to this job.

    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-latest, cont: "bioconductor/bioconductor_docker:devel", rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest" }
          - { os: macOS-latest}
          - { os: windows-latest}
          ## Check https://github.com/r-lib/actions/tree/master/examples
          ## for examples using the http-user-agent
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      NOT_CRAN: true
      TZ: UTC
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:

      - name: Install pyenv (Ubuntu)
        if: runner.os == 'Linux'
        shell: bash -leo pipefail {0}
        run: |
          curl -fsSL https://pyenv.run | bash

      - name: Install pyenv (macOS)
        if: runner.os == 'macOS'
        shell: bash
        run: |
          brew update
          brew install pyenv

      - name: Install pyenv (Windows)
        if: runner.os == 'Windows'
        shell: pwsh {0}
        run: |
          Invoke-WebRequest -UseBasicParsing -Uri "https://raw.githubusercontent.com/pyenv-win/pyenv-win/master/pyenv-win/install-pyenv-win.ps1" -OutFile "./install-pyenv-win.ps1"; &"./install-pyenv-win.ps1"

      - name: Set up pyenv (Ubuntu)
        if: runner.os == 'Linux'
        shell: bash -leo pipefail {0}
        run: |
          echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bash_profile
          echo '[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bash_profile
          echo 'eval "$(pyenv init - bash)"' >> ~/.bash_profile

      - name: Set up pyenv (macOS)
        if: runner.os == 'macOS'
        shell: bash
        run: |
          echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bash_profile
          echo '[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bash_profile
          echo 'eval "$(pyenv init - bash)"' >> ~/.bash_profile

      # - name: Set up pyenv (Windows)
      #   if: runner.os == 'Windows'
      #   shell: pwsh {0}
      #   run: |
      #     # see <https://pyenv-win.github.io/pyenv-win/docs/installation.html#powershell>
      #     # and <https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#example-of-adding-a-system-path>
      #     chcp 65001 #set code page to utf-8
      #     echo ("PYENV=" + $env:USERPROFILE + "\.pyenv\pyenv-win\") >> $env:GITHUB_ENV
      #     echo ("PYENV_ROOT=" + $env:USERPROFILE + "\.pyenv\pyenv-win\") >> $env:GITHUB_ENV
      #     echo ("PYENV_HOME=" + $env:USERPROFILE + "\.pyenv\pyenv-win\") >> $env:GITHUB_ENV
      #     $env:USERPROFILE + "\.pyenv\pyenv-win\shims;" | Out-File -FilePath "$env:GITHUB_PATH" -Append
      #     $env:USERPROFILE + "\.pyenv\pyenv-win\bin;" | Out-File -FilePath "$env:GITHUB_PATH" -Append

      - name: Test pyenv (Ubuntu)
        if: runner.os == 'Linux'
        shell: bash -leo pipefail {0}
        run: |
          pyenv --version

      - name: Test pyenv (macOS)
        if: runner.os == 'macOS'
        shell: bash
        run: |
          pyenv --version

      - name: Test pyenv (Windows)
        if: runner.os == 'Windows'
        shell: pwsh {0}
        run: |
          $env:Path = 'C:\Users\runneradmin\.pyenv\pyenv-win\bin;' + $env:Path
          $env:Path = 'C:\Users\runneradmin\.pyenv\pyenv-win\shims;' + $env:Path
          $env:PYENV = $env:USERPROFILE + '\.pyenv\pyenv-win\'
          $env:PYENV_ROOT = $env:USERPROFILE + '\.pyenv\pyenv-win\'
          $env:PYENV_HOME = $env:USERPROFILE + '\.pyenv\pyenv-win\'
          pyenv --version

      - name: List python 3.1x
        #if: runner.os == 'Linux'
        shell: bash -leo pipefail {0}
        run: |
          pyenv install --list | grep " 3\.1[12345]"
          pyenv --version

      - name: Install python build dependencies (Ubuntu)
        if: runner.os == 'Linux'
        shell: bash -leo pipefail {0}
        run: |
          apt update
          apt-get -yq install \
            build-essential \
            pkg-config \
            ccache \
            gdb \
            lcov \
            libb2-dev \
            libbz2-dev \
            libffi-dev \
            libgdbm-dev \
            libgdbm-compat-dev \
            liblzma-dev \
            libncurses5-dev \
            libreadline6-dev \
            libsqlite3-dev \
            libssl-dev \
            libzstd-dev \
            lzma \
            lzma-dev \
            strace \
            tk-dev \
            uuid-dev \
            xvfb \
            zlib1g-dev

      - name: Install python (Ubuntu)
        if: runner.os == 'Linux'
        shell: bash -leo pipefail {0}
        run: |
          pyenv install 3.13.5

      - name: Test pyenv (Windows)
        if: runner.os == 'Windows'
        shell: pwsh {0}
        run: |
          $env:Path = 'C:\Users\runneradmin\.pyenv\pyenv-win\bin;' + $env:Path
          $env:Path = 'C:\Users\runneradmin\.pyenv\pyenv-win\shims;' + $env:Path
          $env:PYENV = $env:USERPROFILE + '\.pyenv\pyenv-win\'
          $env:PYENV_ROOT = $env:USERPROFILE + '\.pyenv\pyenv-win\'
          $env:PYENV_HOME = $env:USERPROFILE + '\.pyenv\pyenv-win\'
          pyenv install 3.13.5

      - name: Install python in a virtual environment (Ubuntu)
        if: runner.os == 'Linux'
        shell: bash -leo pipefail {0}
        run: |
          pyenv virtualenv 3.13.5 jurassicpark-env

      - name: Confirm presence of virtual environment (Ubuntu)
        if: runner.os == 'Linux'
        shell: bash -leo pipefail {0}
        run: |
          pyenv shell jurassicpark-env
          pyenv virtualenvs

      - name: Install scvelo (Ubuntu)
        if: runner.os == 'Linux'
        shell: bash -leo pipefail {0}
        run: |
          pyenv activate jurassicpark-env
          pip install --no-cache-dir scvelo==0.3.3

      - name: List installed packages (Ubuntu)
        if: runner.os == 'Linux'
        shell: bash -leo pipefail {0}
        run: |
          pyenv activate jurassicpark-env
          python -m pip list --format=freeze

      # - name: Install micromamba environment (Unix)
      #   if: runner.os == 'Linux'
      #   run: |
      #     micromamba env create -n scvelo -c conda-forge -c bioconda scvelo==0.3.2 scipy==1.13.1 tqdm==4.66.5 ipywidgets==8.1.2 libtiff=4.5.1 pillow=10.0.0

      # - name: Install micromamba environment (macOS)
      #   if: runner.os == 'macOS'
      #   run: |
      #     micromamba env create -n scvelo -c conda-forge -c bioconda scvelo==0.3.3 scipy==1.13.1 tqdm ipywidgets

      # - name: Install micromamba environment (Windows)
      #   if: runner.os == 'Windows'
      #   run: |
      #     micromamba env create -n scvelo -c bioconda -c conda-forge scvelo==0.2.5 matplotlib==3.6.3 pandas==1.5.2 numpy==1.21.1
      #   shell: pwsh {0}

      # - name: Export environment (Ubuntu)
      #   if: runner.os != 'Windows'
      #   run: |
      #     micromamba env export -n scvelo > ~/scvelo.yaml

      # - name: Export environment (Windows)
      #   if: runner.os == 'Windows'
      #   run: |
      #     micromamba env export -n scvelo > ~/scvelo.yaml
      #   shell: pwsh {0}

      # - name: Display environment (Ubuntu)
      #   if: runner.os != 'Windows'
      #   run: |
      #     cat ~/scvelo.yaml

      # - name: Display environment (Windows)
      #   if: runner.os == 'Windows'
      #   run: |
      #     type ~/scvelo.yaml
      #   shell: pwsh {0}

      # - name: Checkout Repository
      #   uses: actions/checkout@v3

      # - name: Test scvelo tutorial (Unix; scvelo == 0.3.3)
      #   if: runner.os != 'Windows'
      #   run: |
      #     micromamba activate scvelo
      #     python tests/scvelo/0.3.3.py
      #   shell: bash -el {0}

      # - name: Test scvelo dynamical mode (Unix; scvelo == 0.3.3)
      #   if: runner.os != 'Windows'
      #   run: |
      #     micromamba activate scvelo
      #     python tests/scvelo/0.3.3-dynamical.py
      #   shell: bash -el {0}

      # - name: Test scvelo tutorial (Windows; scvelo == 0.2.5)
      #   if: runner.os == 'Windows'
      #   run: |
      #     micromamba activate scvelo
      #     python tests/scvelo/0.2.5.py
      #   shell: pwsh {0}

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ${{ matrix.config.os }}.yaml
      #     path: ~/scvelo.yaml
