on:
  push:
  pull_request:

name: create-test-upload-macos

jobs:
  build-check-macos:
    runs-on: macOS-latest
    name: macOS-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install pyenv on macOS
        shell: bash -leo pipefail {0}
        run: |
          brew update
          brew install pyenv

      - name: Install pyenv-virtualenv on macOS
        shell: bash -leo pipefail {0}
        run: |
          brew update
          brew install pyenv-virtualenv

      - name: Configure pyenv on macOS
        shell: bash -leo pipefail {0}
        run: |
          echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bash_profile
          echo '[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bash_profile
          echo 'eval "$(pyenv init - bash)"' >> ~/.bash_profile

      - name: Verify pyenv on macOS
        shell: bash -leo pipefail {0}
        run: |
          pyenv --version

      - name: List Python 3.1x versions on macOS
        shell: bash -leo pipefail {0}
        run: |
          pyenv install --list | grep " 3\.1[12345]"

      - name: Install Python 3.13.5 on macOS
        shell: bash -leo pipefail {0}
        run: |
          pyenv install 3.13.5

      - name: Create virtual environment on macOS
        shell: bash -leo pipefail {0}
        run: |
          pyenv virtualenv 3.13.5 jurassicpark-env

      - name: Verify virtual environment on macOS
        shell: bash -leo pipefail {0}
        run: |
          pyenv shell jurassicpark-env
          pyenv virtualenvs

      - name: Install scvelo dependencies on macOS
        shell: bash -leo pipefail {0}
        run: |
          pyenv activate jurassicpark-env
          python -m pip install scvelo==0.3.3 anndata==0.11.4 scipy==1.15.2 zarr==2.18.7 tqdm ipywidgets

      - name: Save installed packages on macOS
        shell: bash -leo pipefail {0}
        run: |
          mkdir -p outputs
          pyenv activate jurassicpark-env
          python -m pip list --format=freeze > "outputs/${RUNNER_OS}-pyenv.txt"
          cat "outputs/${RUNNER_OS}-pyenv.txt"

      - name: Run scvelo smoke test on macOS
        shell: bash -leo pipefail {0}
        run: |
          pyenv activate jurassicpark-env
          python tests/scvelo/0.3.3.py

      - name: Upload installed packages artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ runner.os }}-pyenv-packages
          path: outputs/${{ runner.os }}-pyenv.txt
          if-no-files-found: error
